"""
features.py - Feature Engineering Module for ShadowTrace.

This module transforms raw cybersecurity event logs into structured numerical
behavioral features aggregated by source IP address, preparing the data
for future machine-learning anomaly detection models.
"""

from datetime import datetime
import pandas as pd


def extract_features(events):
    """
    Analyzes a list of security event dictionaries, groups them by source IP,
    and calculates behavioral profile metrics for each IP address.

    Parameters:
        events (list): List of security event dictionaries.

    Returns:
        pd.DataFrame: A pandas DataFrame where each row represents one source IP,
                      with source_ip as a regular column and numerical feature columns.
    """
    # Step 1: Group events by source IP address
    # This collects all actions taken by each IP into its own list.
    events_by_ip = {}
    for event in events:
        ip = event.get("source_ip")
        if ip not in events_by_ip:
            events_by_ip[ip] = []
        events_by_ip[ip].append(event)

    feature_rows = []

    # Step 2: Iterate over each IP and compute its behavioral statistics
    for ip, ip_events in events_by_ip.items():
        # Initialize count variables for each event type
        failed_login_count = 0
        successful_login_count = 0
        privilege_escalation_count = 0
        server_access_count = 0
        data_transfer_count = 0

        # Tally up event types for this specific IP
        for event in ip_events:
            event_type = event.get("event_type")
            if event_type == "LOGIN_FAILED":
                failed_login_count += 1
            elif event_type == "LOGIN_SUCCESS":
                successful_login_count += 1
            elif event_type == "PRIVILEGE_ESCALATION":
                privilege_escalation_count += 1
            elif event_type == "INTERNAL_SERVER_ACCESS":
                server_access_count += 1
            elif event_type == "DATA_TRANSFER":
                data_transfer_count += 1

        # Total number of events generated by this IP
        total_event_count = len(ip_events)

        # Step 3: Calculate activity duration in seconds
        # Convert string timestamps to datetime objects to find min (earliest) and max (latest)
        timestamps = [
            datetime.strptime(event["timestamp"], "%Y-%m-%d %H:%M:%S")
            for event in ip_events
        ]
        first_time = min(timestamps)
        last_time = max(timestamps)

        # If an IP has only 1 event, first_time == last_time, resulting in 0 seconds duration
        activity_duration_seconds = int((last_time - first_time).total_seconds())

        # Step 4: Assemble the feature row dictionary for this IP
        feature_rows.append({
            "source_ip": ip,
            "failed_login_count": failed_login_count,
            "successful_login_count": successful_login_count,
            "privilege_escalation_count": privilege_escalation_count,
            "server_access_count": server_access_count,
            "data_transfer_count": data_transfer_count,
            "total_event_count": total_event_count,
            "activity_duration_seconds": activity_duration_seconds,
        })

    # Step 5: Convert the list of dictionaries into a pandas DataFrame
    # source_ip remains a normal column (the default integer index is used)
    features_df = pd.DataFrame(feature_rows)

    return features_df
