"""
features.py - Feature Engineering Module for ShadowTrace.

This module transforms raw cybersecurity event logs into structured numerical
behavioral features aggregated by source IP address, preparing the data
for future machine-learning anomaly detection models.
"""

from datetime import datetime
import pandas as pd


def extract_features(events):
    """
    Analyzes a list of security event dictionaries, groups them by source IP,
    and calculates behavioral profile metrics for each IP address.

    Parameters:
        events (list): List of security event dictionaries.

    Returns:
        pd.DataFrame: A pandas DataFrame where each row represents one source IP,
                      with source_ip as a regular column and numerical feature columns.
    """
    # Step 1: Group events by source IP address
    # This collects all actions taken by each IP into its own list.
    events_by_ip = {}
    for event in events:
        ip = event.get("source_ip")
        if ip not in events_by_ip:
            events_by_ip[ip] = []
        events_by_ip[ip].append(event)

    feature_rows = []

    # Step 2: Iterate over each IP and compute its behavioral statistics
    for ip, ip_events in events_by_ip.items():
        # Initialize count variables for each event type
        failed_login_count = 0
        successful_login_count = 0
        privilege_escalation_count = 0
        server_access_count = 0
        data_transfer_count = 0

        # Tally up event types for this specific IP
        for event in ip_events:
            event_type = event.get("event_type")
            if event_type == "LOGIN_FAILED":
                failed_login_count += 1
            elif event_type == "LOGIN_SUCCESS":
                successful_login_count += 1
            elif event_type == "PRIVILEGE_ESCALATION":
                privilege_escalation_count += 1
            elif event_type == "INTERNAL_SERVER_ACCESS":
                server_access_count += 1
            elif event_type == "DATA_TRANSFER":
                data_transfer_count += 1

        # Total number of events generated by this IP
        total_event_count = len(ip_events)

        # Step 3: Calculate activity burst duration and behavioral rates
        # Instead of measuring the full multi-day lifespan of an IP (which masks attack velocity),
        # we segment events into distinct "activity bursts" using an inactivity threshold.
        # An activity burst represents a continuous session where consecutive events
        # occur within 600 seconds (10 minutes) of each other.
        sorted_ip_events = sorted(
            ip_events,
            key=lambda e: datetime.strptime(e["timestamp"], "%Y-%m-%d %H:%M:%S"),
        )

        if len(sorted_ip_events) <= 1:
            activity_duration_seconds = 0
            failed_login_rate = 0.0
            event_rate = 0.0
        else:
            # Segment events into bursts separated by > 10 minutes (600s) of idle time
            BURST_GAP_THRESHOLD_SECONDS = 600
            bursts = []
            current_burst = [sorted_ip_events[0]]

            for current_event in sorted_ip_events[1:]:
                current_time = datetime.strptime(current_event["timestamp"], "%Y-%m-%d %H:%M:%S")
                prev_time = datetime.strptime(current_burst[-1]["timestamp"], "%Y-%m-%d %H:%M:%S")
                gap_seconds = (current_time - prev_time).total_seconds()

                if gap_seconds <= BURST_GAP_THRESHOLD_SECONDS:
                    current_burst.append(current_event)
                else:
                    bursts.append(current_burst)
                    current_burst = [current_event]
            bursts.append(current_burst)

            # Helper to calculate the time span of a burst
            def calculate_burst_duration(b):
                start = datetime.strptime(b[0]["timestamp"], "%Y-%m-%d %H:%M:%S")
                end = datetime.strptime(b[-1]["timestamp"], "%Y-%m-%d %H:%M:%S")
                return (end - start).total_seconds()

            # Select the peak activity burst (highest concentration of events)
            peak_burst = max(bursts, key=lambda b: (len(b), calculate_burst_duration(b)))
            activity_duration_seconds = int(calculate_burst_duration(peak_burst))

            # Step 4: Calculate behavioral rate features during the peak burst
            # Safely handle duration of 0 to avoid ZeroDivisionError
            if activity_duration_seconds > 0:
                peak_failed_logins = sum(1 for e in peak_burst if e.get("event_type") == "LOGIN_FAILED")
                failed_login_rate = round(peak_failed_logins / activity_duration_seconds, 4)
                event_rate = round(len(peak_burst) / activity_duration_seconds, 4)
            else:
                failed_login_rate = 0.0
                event_rate = 0.0

        # Step 5: Calculate failed login ratio across all login attempts
        # Measures the proportion of login attempts that failed (0.0 if no logins)
        total_logins = failed_login_count + successful_login_count
        failed_login_ratio = round(failed_login_count / total_logins, 4) if total_logins > 0 else 0.0

        # Step 6: Assemble the feature row dictionary for this IP
        feature_rows.append({
            "source_ip": ip,
            "failed_login_count": failed_login_count,
            "successful_login_count": successful_login_count,
            "privilege_escalation_count": privilege_escalation_count,
            "server_access_count": server_access_count,
            "data_transfer_count": data_transfer_count,
            "total_event_count": total_event_count,
            "activity_duration_seconds": activity_duration_seconds,
            "failed_login_rate": failed_login_rate,
            "event_rate": event_rate,
            "failed_login_ratio": failed_login_ratio,
        })

    # Step 5: Convert the list of dictionaries into a pandas DataFrame
    # source_ip remains a normal column (the default integer index is used)
    features_df = pd.DataFrame(feature_rows)

    return features_df
